services:
  backend:
    container_name: backend-service
    build: ./
    ports:
      - "5500:5500"
    environment:
      PORT: 5500
      SERVER_URL: "http://localhost:5500"
      NODE_ENV: development
      DB_URI: "mongodb+srv://ansulsingh171:Anshul8012@cluster0.9drme2k.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
      JWT_SECRET: "secret"
      JWT_EXPIRES_IN: "1d"
      ARCJET_KEY: "ajkey_01jvvbpcd3fx281rrgpj18fgns"
      ARCJET_ENV: development
    develop:
      watch:
        - path: ./package.json
          action: rebuild
        - path: ./package-lock.json
          action: rebuild
        - path: ./subscription
          target: /app
          action: sync
